version: '3.7'

services:
  client:
    stdin_open: true
    build: ./client
    ports:
      - '5000:3000'
    depends_on:
      - api
    image: wyfy/netflix_client:1.0

  api:
    env_file:
      - .env
    build: ./
    ports:
      - '5001:3000'
    depends_on:
      - mongo
    image: wyfy/netflix_api:1.0

  mongo:
    image: mongo
    ports:
      - '27017:27017'
